<?php

use Illuminate\Database\Seeder;

class TerminosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $terminos = [
            ['pais_id' => '45', 'terminos' => 'Términos y Condiciones de Uso del Sitio 1.         Materiales Presentados. A menos que se solicite específicamente, no pedimos ni deseamos recibir ninguna información confidencial, secreta o patrimonial, ni otro material de usted a través del Sitio Web, por correo electrónico o de cualquier otra manera. Cualquier información, trabajos creativos, demostración, ideas, sugerencias, conceptos, métodos, sistemas, diseños, planes, técnicas u otros materiales que nos haya mandado o presentado (incluyendo, por ejemplo y sin limitación, aquello que usted presenta o envía a nuestros grupos de chateo, tablas de mensajes y/o a nuestros ‘blogs’, o que nos manda vía correo electrónico) ("Materiales Presentados") se considerará como no confidencial o secreto y que puede ser usado por nosotros de cualquier manera consistente con la Politica de Privacidad  del Sitio Web. Al presentarnos o mandarnos Materiales Presentados, usted: (i) representa y garantiza que los Materiales Presentados son originales suyos, que ninguna otra persona tiene ningún derecho sobre ellos, y que cualquier "derecho moral" sobre los Materiales Presentados ha sido renunciado, y (ii) usted nos concede, a nosotros y a nuestros afiliados, derecho y licencia libres de regalías, sin restricciones, mundiales, perpetuos, irrevocables, no exclusivos y totalmente transferibles, que pueden ser cedidos y sub-licenciados, para usar, copiar, reproducir, modificar, adaptar, publicar, traducir, crear trabajos derivados de, distribuir, ejecutar, exponer e incorporar en otros trabajos cualquiera de los Materiales Presentados (todos o en parte) en cualquier forma, medio o tecnología no conocida o por desarrollar, incluyendo propósitos promocionales y/o comerciales. No podemos ser responsables de conservar ningún Material Presentado proporcionado por usted y podemos borrar o destruir dicho Material Presentado en cualquier momento.
 
2.         Conducta Prohibida del Usuario. Usted garantiza y está de acuerdo en que, mientras use el Sitio Web y los diversos servicios y artículos que se ofrecen en o a través del Sitio Web, usted no: (a) personalizará a ninguna persona o entidad ni desvirtuará su afiliación con alguna otra persona o entidad; (b)  insertará su propio anuncio, posicionamiento de marca o algún otro contenido promocional o el de un tercero  en cualquiera de los contenidos, materiales o servicios o materiales del Sitio Web (por ejemplo, sin limitación, en una actualización RSS o en un programa de radio grabado (podcast) recibido de Time Inc. o de algún otro modo a través del Sitio Web), ni usará, redistribuirá, republicará o explotará dichos contenidos o servicios con cualquier otro propósito adicional comercial o promocional; ni (c) intentará ganar acceso no autorizado a otros sistemas de cómputo a través del Sitio Web. Usted no: (i) participará en navegar por la red, en "raspar (scraping) la pantalla", "raspar (scraping) la base da datos", en recolectar direcciones de correo electrónico, direcciones inalámbricas u otra información personal o de contactos, o cualquier otro medio automático de obtener listas de usuarios u otra información de o a través del sitio Web o de los servicios ofrecidos en o a través del Sitio Web, incluyendo, sin limitación, cualquier información que se encuentre en algún servidor o base de datos relacionada con el Sitio Web o los servicios ofrecidos en o a través del Sitio Web; (ii) obtendrá o intentará obtener acceso no autorizado a los sistemas de cómputo, materiales o información por cualquier medio; (iii) usará el Sitio Web o los servicios puestos a su disposición en o a través del Sitio Web de alguna manera con la intención de interrumpir, dañar, deshabilitar, sobrecargar o deteriorar el Sitio Web o dichos servicios, incluyendo, sin limitación, mandar mensajes masivos no solicitados o "inundar" servidores con solicitudes; (iv) usará el Sitio Web o los servicios o artículos del Sitio Web en violación de la propiedad intelectual o de otros derechos legales o patrimoniales de Time Inc o de algún tercero; ni (v) usará el Sitio Web o los servicios del Sitio Web en violación de cualquier ley aplicable. Usted se obliga además, a no intentar (o alentar o apoyar el intento de otro) a embaucar, destruir, decodificar, o de otro modo alterar o interferir con el Sitio Web o con los servicios del Sitio Web, o con cualquier contenido del mismo, o hacer cualquier uso no autorizado del mismo. Usted se obliga a no usar el Sitio Web de alguna manera que pudiera dañar, deshabilitar, sobrecargar o deteriorar el Sitio Web o interferir con que cualquier otra persona pueda usar o disfrutar del Sitio Web o de cualquiera de sus servicios. Usted no obtendrá ni intentará obtener algún material o información a través de cualquier medio que no haya sido estipulado o puesto a la disposición del público intencionalmente a través del Sitio Web.
 
3.         Foros Públicos. Time Inc. puede, de vez en cuando, tener servicios de mensajería, servicios de chateo, tableros de noticias, blogs, otros foros y otros servicios disponibles en o a través del Sitio Web. Además de cualquier otra normatividad y regulación que podamos publicar con respecto a un servicio en particular, usted se obliga a no cargar, informar, transmitir, distribuir o de otra manera publicar a través del Sitio Web o de cualquier servicio o artículo puesto a la disposición en o a través del Sitio Web, cualquier material que (i) restrinja o inhiba a cualquier otro usuario de usar y disfrutar del Sitio Web o de los servicios del Sitio Web, (ii) sea fraudulento, ilegal, amenazante, abusivo, hostigante, calumnioso, difamatorio, obsceno, vulgar, ofensivo, pornográfico, profano, sexualmente explícito o indecente, (iii) constituya o aliente conductas que pudieran constituir una ofensa criminal, dar lugar a responsabilidad civil o de otro modo violar cualquier ley local, estatal, nacional o internacional, (iv) viole, plagie o infrinja los derechos de terceros incluyendo, sin limitación, derechos de autor, marcas comerciales, secretos comerciales, confidencialidad, contratos, patentes, derechos de privacidad o publicidad o cualquier otro derecho de propiedad, (v) contenga un virus, elemento de espionaje u otro componente dañino, (vi) contenga enlaces fijos, publicidad, cartas de cadenas o esquemas de pirámides de cualquier tipo, o (vii) constituya o contenga indicaciones de origen, endosos o declaraciones de hechos falsos o engañosos. Usted además se obliga a no personificar a cualquier otra persona o entidad, ya sea real o ficticia, incluyendo cualquier persona de Time Inc. Usted tampoco puede ofrecer comprar o vender algún producto o servicio en o a través de sus comentarios presentados en nuestros foros. Solamente usted es responsable del contenido y de las consecuencias de cualquiera de sus actividades.
 
4.         Derecho de Monitoreo y Control Editorial. Time Inc. se reserva el derecho, pero no tiene la obligación, de monitorear y/o revisar todos los materiales enviados al Sitio Web o a través de los servicios o artículos del Sitio Web por los usuarios, y Time Inc. no es responsable de dichos materiales enviados por los usuarios. Sin embargo, Time Inc. se reserva el derecho en todo momento de divulgar cualquier información que sea necesaria para satisfacer cualquier ley, reglamento o solicitud gubernamental, o de editar, rehusarse a colocar o a quitar cualquier información o materiales, todos o en parte, que a discreción únicamente de Time Inc. sean censurables o en violación de estos Términos de Uso, de las políticas de Time Inc o de la ley aplicable. También podemos imponer límites sobre ciertos artículos de los foros o restringir su acceso a parte o a todos los foros sin notificación o sanción, si creemos que usted está en incumplimiento de las directrices establecidas en este párrafo, nuestros términos y condiciones o la ley aplicable, o por cualquier otra razón sin notificación o responsabilidad.
 
5.      Información Privada o Delicada en Foros Públicos. Es importante recordar que los comentarios presentados en un foro pueden ser registrados y almacenados en múltiples lugares, tanto en nuestro Sitio Web como en otra parte en Internet, los cuales pueden ser accesibles durante mucho tiempo y no se tiene control sobre quién los leerá eventualmente. Es por lo tanto importante que tenga usted cuidado y sea selectivo acerca de la información personal que divulgue acerca de usted y de otros, y en especial, no debe divulgar información delicada, patrimonial o confidencial en sus comentarios en nuestros foros públicos.
'],
            ['pais_id' => '64', 'terminos' => 'Terms and Conditions of Use of the Site The following terms and conditions (the "Terms and Conditions") govern your use of this website and any content available through or through this website, including any content derived therefrom (the "Website" ). Time Inc. ("Time Inc." or "us") has made available to you the Website. We may change the Terms and Conditions from time to time, at any time without notice, only by posting the changes on the Website. BY USING THE WEBSITE, YOU ACCEPT AND AGREE TO THESE TERMS AND CONDITIONS WITH REGARD TO YOUR USE OF THE WEBSITE. If you do not agree to these Terms and Conditions, you may not access or use the Website in any other way.
 
1. Property Rights. Between you and Time Inc., Time Inc. is the sole and exclusive owner of all rights, title and interests in and to the Website, all content (including, for example, audio, photographs, illustrations, graphics, other means Visuals, videos, copies, texts, software, titles, crash wave files, etc.), codes, data and materials thereof, appearance and environment, design and organization of the Website and compilation of contents , Codes, data and materials on the Website, including but not limited to, any copyrights, trademark rights, patent rights, database rights, moral rights, sui generis rights and other intellectual property and economic rights of the same. Your use of the Website does not grant ownership of any content, codes, data or materials that you may access on or through the Website.
 
2. Limited License. You may access and view the content of the Website from your computer or from any other device and, unless otherwise stated in these Terms and Conditions or on the Website, make copies or individual impressions of the content of the Website For your personal, internal use only. The use of the Website and the services offered on or through the Website are for your personal, non-commercial use only.
 
3. Prohibited Use. Any distribution, publication or commercial or promotional exploitation of the Website, or any of the contents, codes, data or materials on the Website, is strictly prohibited, unless you have received the express prior written permission of the authorized personnel Of Time Inc. or any other applicable rights holder. Except as expressly permitted in this agreement, you may not download, report, display, publish, copy, reproduce, distribute, transmit, modify, perform, broadcast, transfer, create derivative works from, sell, or otherwise Exploit any of the contents, codes, data or materials on or available through the Website. You further agree not to alter, edit, delete, remove, or otherwise change the meaning or appearance of, or change the purpose of, any of the content, codes, data or materials on or available through the Website , Including, without limitation, alteration or withdrawal of any trademark, trademark, logo, service mark or any other proprietary content or proprietary rights notice. You acknowledge that you do not acquire any ownership rights in downloading any copyrighted material from or through the Website. If you make other use of the Website, or the content, codes, data or materials that are available there or that are available through the Website, except as stipulated above, you may violate the copyright laws. Author and other laws of the United States and other countries, as well as applicable state laws, and may be subject to legal liability for such unauthorized use.

4. Trademarks. Trademarks, logos, service marks, trademarks (collectively the "Trademarks") displayed on the Website or in the contents available through the Website are registered and unregistered Time Inc. Trademarks and others, and Can not be used with respect to products and / or services that are not related, associated or sponsored by their rights holders and that may cause confusion to customers, or in any way that denigrates or discredits their rights holders. All Trademarks that are not of Time Inc. appearing on the Website or in or through the services of the Website, if any, are the property of their respective owners. Nothing contained in the Website shall be construed as granting, by implication, rejection, or otherwise, any license or right to use any Trademark displayed on the Website without the written permission of Time Inc. or third parties May own such Trademark. Misuse of the Trademarks displayed on the Website or in or through any of the services of the Website is strictly prohibited.
 
5. User Information. In the course of your use of the Website and / or the services made available to you on or through the Website, you may be asked to provide us with certain personalized information (such information hereinafter "User Information") . The policies of use and collection of information of Time Inc. with respect to the privacy of said User Information are established in the Privacy Policy of the Website, which is incorporated to the same like reference for all the purposes. You acknowledge and agree to be solely responsible for the accuracy of the User Information content.
'],
            ['pais_id' => '178', 'terminos' => 'Términos y Condiciones de Uso del Sitio
            1.      Enlaces con el Sitio Web. Usted está de acuerdo en que si incluye un enlace (link) de cualquier otro sitio web al Sitio Web, dicho enlace se abrirá en una nueva ventana navegadora y se enlazará con la versión completa de una página formateada HTML de este Sitio Web. Usted no tiene permitido enlazarse directamente a ninguna imagen almacenada en el Sitio Web o en nuestros servicios, como sería usar un método de enlace "en-línea" para provocar que la imagen almacenada por nosotros fuera expuesta en otro sitio web. Usted se obliga a no descargar o usar imágenes almacenadas en este Sitio Web en otro sitio web, con cualquier propósito, incluyendo, sin limitación, publicar dichas imágenes en otro sitio web. Usted se obliga a no enlazarse de cualquier otro sitio web a este Sitio Web de tal manera que el Sitio Web, o cualquier página del Sitio Web, esté "enmarcado", rodeado u ofuscado por los contenidos, materiales o posicionamientos de marca de cualquier tercero. Nos reservamos todos nuestros derechos bajo la ley para insistir en que cualquier enlace al Sitio Web sea descontinuado y a revocar su derecho a enlazarse al Sitio Web de cualquier otro sitio web, en cualquier momento en el que le mandemos notificación por escrito.
 
2.      Indemnización. Usted se obliga a defender, indemnizar y a sacar a Time Inc. y a los directores, funcionarios, empleados y agentes de Time Inc. y sus afiliados en paz y a salvo de cualquier demanda, responsabilidad, costos y gastos, de cualquier naturaleza, incluyendo honorarios de abogados, en que incurriera como resultado del uso del Sitio Web, su colocación o transmisión de cualquier mensaje, contenido, información, software u otros materiales a través del Sitio Web, o su incumplimiento o violación de la ley o de estos Términos y Condiciones. Time Inc. se reserva el derecho, a su propio costo, de asumir la defensa y control exclusivos de cualquier asunto de otra manera sujeto a indemnización por parte suya, y en dicho caso, usted se obliga a cooperar con Time Inc. en la defensa de dicha demanda.
 
3.      Órdenes de Productos y Servicios. Podemos poner ciertos productos a la disposición de visitantes y registrados del Sitio Web. Si usted ordena cualquier producto, por el presente documento usted representa y garantiza que tiene 18 años de edad o más. Se obliga a pagar la totalidad de los precios de cualquier compra que haga, ya sea con tarjeta de crédito/débito concurrente con su orden en línea o por otro medio de pago aceptable para Time Inc. Usted se obliga a pagar todos los impuestos aplicables. Si el pago no es recibido por nosotros de parte del emisor de su tarjeta de crédito o débito o de sus agentes, usted se obliga a pagar todas las cantidades debidas al momento de la reclamación por nuestra parte. Algunos productos que usted compra y/o descarga en o a través del Sitio Web pueden estar sujetos a términos y condiciones adicionales que le serán presentados al momento de dicha compra o descarga.
 
4.      Sitios Web de Terceros. Usted puede enlazar (link) del Sitio Web a sitios web de terceros y terceros pueden enlazarse al Sitio Web ("Sitios Enlazados"). Usted reconoce y está de acuerdo en que nosotros no tenemos responsabilidad sobre la información, contenido, productos, servicios, anuncios, códigos u otros materiales que puedan o no puedan ser proporcionados por o a través de los Sitios Enlazados, aún si son propiedad de o son dirigidos por afiliados nuestros. Los enlaces (links) a Sitios Enlazados no constituyen un aval o patrocinio nuestro de dichos sitios web o de la información, contenido, productos, servicios, anuncios, códigos u otros materiales presentados en o a través de dichos sitios web. La inclusión de cualquier enlace a dichos sitios en nuestro Sitio no implica el aval, patrocinio o recomendación de ese sitio de Time Inc. Time Inc. rechaza cualquier responsabilidad por los enlaces (1) de otro sitio web a este Sitio Web y (2) a otro sitio web de este Sitio Web. Time Inc. no puede garantizar los estándares de cualquier sitio web al cual se le proporcionen enlaces en este Sitio Web, ni será Time Inc. responsable de los contenidos de dichos sitios, o de cualquier enlace subsecuente. Time Inc. no representa o garantiza que los contenidos del sitio web de algún tercero sean exactos, que cumplan con la ley estatal o federal, o que cumplan con las leyes de derechos de autor o con otras leyes de propiedad intelectual. Time Inc. tampoco es responsable de cualquier forma de transmisión recibida de cualquier sitio web enlazado. Cualquier confianza depositada en los contenidos de un sitio web de terceros es hecha por su propio riesgo y usted asume todas las responsabilidades y consecuencias que resulten de dicha confianza.
 
5.      Agente de Derechos de Autor.
 
Respetamos los derechos de propiedad intelectual de otros y requerimos que las personas que usen el Sitio Web, o los servicios o artículos puestos a su disposición en o a través del Sitio Web, hagan lo mismo. Si usted cree que su trabajo ha sido copiado de un modo que constituya una infracción a los derechos de autor, por favor mande la siguiente información a Agente de Derechos de Autor de Time Inc., designado como tal de conformidad con la l pagina web nombrado abajo:
 
Su dirección, número de teléfono y dirección de correo electrónico;
Una descripción del trabajo con derechos de autor que usted reclama ha sido infringido;
Una descripción de donde se localiza el supuesto material infringido;
Una declaración suya de que usted cree de buena fe que el uso en disputa no está autorizado por el dueño de los derechos de autor, su agente o la ley;
Una firma electrónica o física de la persona autorizada para actuar en nombre del dueño del interés de los derechos de autor; y
Una declaración suya, hecha bajo pena de perjurio, de que la información antes mencionada en su notificación es exacta y de que usted es el dueño de los derechos de autor o está autorizado para actuar en nombre del dueño de los derechos de autor.
'],
            ['pais_id' => '187', 'terminos' => 'Términos y Condiciones de Uso del Sitio.

            1.      RENUNCIA DE GARANTÍAS. EL SITIO WEB, INCLUYENDO, SIN LIMITACIÓN, TODOS LOS SERVICIOS, CONTENIDOS, FUNCIONES Y MATERIALES PROPORCIONADOS A TRAVÉS DEL SITIO WEB, SON PROPORCIONADOS "TAL COMO ESTÉN", "COMO SE PONEN A LA DISPOSICIÓN", SIN GARANTÍA DE NINGÚN TIPO, YA SEA EXPRESA O IMPLÍCITA, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER GARANTÍA DE INFORMACIÓN, DATOS, SERVICIOS DE PROCESAMIENTO DE DATOS, ACCESO ILIMITADO O ININTERRUMPIDO, CUALQUIER GARANTÍA CON RESPECTO A LA DISPONIBILIDAD, INTERPRETABILIDAD, NO INTERPRETABILIDAD, EXACTITUD, PRECISIÓN, RECTITUD, PERFECCIÓN, CONCLUSIÓN, UTILIDAD, O CONTENIDO DE LA INFORMACIÓN, Y CUALQUIER GARANTÍA DE TÍTULO, NO-INFRACCIÓN, COMERCIABILIDAD O APTITUD PARA UN PROPÓSITO EN PARTICULAR, Y EN EL PRESENTE RENUNCIAMOS A CUALQUIERA Y A TODAS DICHAS GARANTÍAS, EXPRESAS E IMPLÍCITAS. NO GARANTIZAMOS QUE EL SITIO WEB O LOS SERVICIOS, CONTENIDOS, FUNCIONES O MATERIALES PROPORCIONADOS A TRAVÉS DEL SITIO WEB SERÉN OPORTUNOS, SEGUROS, ININTERRUMPIDOS O LIBRES DE ERROR, O QUE LOS DEFECTOS SERÉN CORREGIDOS. NO DAMOS GARANTÍA DE QUE EL SITIO WEB O DE QUE LOS SERVICIOS PROPORCIONADOS CUMPLIRÉN CON LOS REQUERIMIENTOS DE LOS USUARIOS. NINGÚN CONSEJO, RESULTADOS O INFORMACIÓN, YA SEA ORAL O ESCRITO, QUE USTED OBTENGA DE NOSOTROS A TRAVÉS DEL SITIO WEB CREARÉ ALGUNA GARANTÍA QUE NO HAYA SIDO ESTABLECIDA EXPRESAMENTE EN EL PRESENTE. TIME INC. TAMPOCO ASUME NINGUNA RESPONSABILIDAD, Y NO SERÉ RESPONSABLE DE CUALQUIER DAÑO A, O DE CUALQUIER VIRUS QUE PUDIERA INFECTAR SU EQUIPO A CAUSA DE SU ACCESO A, USO DE, O NAVEGACIÓN EN EL SITIO WEB O POR DESCARGAR CUALQUIERA DE LOS MATERIALES, DATOS, TEXTOS, IMÉGENES, CONTENIDOS DE VIDEO O CONTENIDOS DE AUDIO DEL SITIO WEB. SI USTED NO ESTÉ SATISFECHO CON EL SITIO WEB, SU ÚNICA SOLUCIÓN ES DESCONTINUAR USANDO EL SITIO WEB.
 
TRATAMOS DE ASEGURAR QUE LA INFORMACIÓN PUBLICADA EN EL SITIO WEB ES CORRECTA Y ACTUALIZADA. NOS RESERVAMOS EL DERECHO DE CAMBIAR O HACER CORRECCIONES A CUALQUIER INFORMACIÓN PROPORCIONADA EN EL SITIO WEB EN CUALQUIER MOMENTO Y SIN NINGÚN AVISO PREVIO. TIME INC. NI AVALA NI ES RESPONSABLE DE LA EXACTITUD O VERACIDAD DE CUALQUIER OPINIÓN, CONSEJO O DECLARACIÓN EN EL SITIO WEB, NI DE CUALQUIER PUBLICACIÓN OFENSIVA, DIFAMATORIA, OBSCENA, INDECENTE, ILEGAL O VIOLATORIA HECHA EN EL MISMO POR CUALQUIER PERSONA A NO SER UN EMPLEADO PORTAVOZ AUTORIZADO DE TIME INC. EN SU CARÉCTER OFICIAL (INCLUYENDO, SIN LIMITACIÓN, OTROS USUARIOS DEL SITIO WEB). ES SU RESPONSABILIDAD EVALUAR LA EXACTITUD, CONCLUSIÓN O UTILIDAD DE CUALQUIER INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO DISPONIBLE A TRAVÉS DEL SITIO WEB. POR FAVOR BUSQUE EL CONSEJO DE PROFESIONALES, SEGÚN SEA APROPIADO, CON RESPECTO A LA EVALUACIÓN DE CUALQUIER INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO ESPECÍFICO, INCLUYENDO PERO NO LIMITADO A, INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO FINANCIERO, DE SALUD O DE ESTILO DE VIDA.
 
PREVIO A LA REALIZACIÓN DE UNA COMPRA O VENTA DE CUALQUIER VALOR O INVERSIÓN, LE ACONSEJAMOS QUE CONSULTE CON SU CORREDOR O CON OTRO ASESOR FINANCIERO PARA VERIFICAR PRECIOS Y OTRA INFORMACIÓN. NO TENDREMOS NINGUNA RESPONSABILIDAD DE DECISIONES DE INVERSIÓN BASADAS EN, O DE RESULTADOS OBTENIDOS DE, EL CONTENIDO PROPORCIONADO EN EL PRESENTE. NADA CONTENIDO EN EL SITIO WEB SERÉ INTERPRETADO COMO CONSEJO DE INVERSIÓN. TIME INC. NO ES UN CORREDOR DE BOLSA REGISTRADO NI UN CONSULTOR DE INVERSIONES Y NO DA CONSEJOS SOBRE INVERSIONES NI RECOMIENDA UN PRODUCTO SOBRE OTRO.
 
SIN LIMITACIÓN DE LO ANTES MENCIONADO EN ESTA SECCIÓN, TIME INC, Y SUS AFILIADOS, PROVEEDORES Y PERSONAS QUE OTORGAN LAS LICENCIAS NO DAN GARANTÍAS NI REPRESENTACIONES CON RESPECTO A CUALQUIER PRODUCTO O SERVICIO ORDENADO O PROPORCIONADO VÍA EL SITIO WEB, Y EN EL PRESENTE RENUNCIAN, Y USTED EN EL PRESENTE DESISTE, DE CUALQUIERA Y DE TODAS LAS GARANTÍAS Y REPRESENTACIONES HECHAS A LITERATURA EN PRODUCTOS O SERVICIOS, A PREGUNTAS HECHAS FRECUENTEMENTE EN DOCUMENTOS Y DE ALGUNA OTRA MANERA EN EL SITIO WEB O EN CORRESPONDENCIA CON TIME INC. O CON SUS AGENTES. CUALQUIER PRODUCTO O SERVICIO ORDENADO O PROPORCIONADO VÍA EL SITIO WEB ES PROPORCIONADO POR TIME INC. "TAL COMO ESTÉ", EXCEPTO AL GRADO, SI SE DIERA EL CASO, DE ESTAR DE OTRO MODO ESTABLECIDO POR ESCRITO, EN UN CONTRATO DE LICENCIA O VENTA CELEBRADO POR SEPARADO ENTRE USTED Y TIME INC. O SU PROVEEDOR O LA PERSONA QUE OTORGA LA LICENCIA.

2.      LÍMITE DE RESPONSABILIDAD. EN NINGÚN CASO, INCLUYENDO PERO NO LIMITADO A NEGLIGENCIA, SERÉ RESPONSABLE TIME INC., O CUALQUIERA DE SUS DIRECTORES, FUNCIONARIOS, EMPLEADOS, AGENTES O PROVEEDORES, DEL CONTENIDO O DE LOS SERVICIOS (CONJUNTAMENTE, LAS "ENTIDADES PROTEGIDAS") DE CUALQUIER DAÑO DIRECTO, INDIRECTO, ESPECIAL, INCIDENTAL, CONSECUENTE, EJEMPLAR O PUNITIVO COMO RESULTADO DE, O DIRECTA O INDIRECTAMENTE RELACIONADO CON, EL USO DE, O LA INCAPACIDAD DE USAR EL SITIO WEB O LOS CONTENIDOS, MATERIALES Y FUNCIONES RELACIONADOS CON EL MISMO, SU PROVISIÓN DE INFORMACIÓN VÍA EL SITIO WEB, NEGOCIOS PERDIDOS O VENTAS PERDIDAS, AÚN CUANDO DICHA ENTIDAD PROTEGIDA HAYA SIDO ASESORADA SOBRE LA POSIBILIDAD DE DICHOS DAÑOS. ALGUNAS JURISDICCIONES NO PERMITEN LA LIMITACIÓN O EXCLUSIÓN DE RESPONSABILIDAD POR DAÑOS INCIDENTALES O INDIRECTOS ASÍ QUE ALGUNOS DE LAS LIMITACIONES ARRIBA MENCIONADAS NO APLICAN A ALGUNOS USUARIOS. EN NINGÚN CASO SERÉN RESPONSABLES LAS ENTIDADES PROTEGIDAS POR O EN RELACIÓN CON CUALQUIER CONTENIDO PUBLICADO, TRANSMITIDO, INTERCAMBIADO O RECIBIDO POR O EN NOMBRE DE CUALQUIER USUARIO O DE OTRA PERSONA EN O A TRAVÉS DEL SITIO WEB. EN NINGÚN CASO LA SUMA TOTAL DE LAS RESPONSABILIDADES DE LAS ENTIDADES PROTEGIDAS HACIA USTED, POR TODOS LOS DAÑOS, PÉRDIDAS Y CAUSAS DE ACCIÓN PENAL (YA SEA POR CONTRATO O POR AGRAVIO, INCLUYENDO PERO NO LIMITADO A, NEGLIGENCIA O DE ALGUNA OTRA MANERA) QUE RESULTEN DE LOS TÉRMINOS Y CONDICIONES O DEL USO QUE USTED HAGA DEL SITIO WEB, DEBERÉ EXCEDER EN LA SUMA TOTAL, LA CANTIDAD, SI LA HUBIERA, PAGADA POR USTED A TIME INC. POR EL USO DEL SITIO WEB O POR LA COMPRA DE PRODUCTOS VÍA EL SITIO WEB.
 
3.      Ataques Fotosensibles. Un muy pequeño porcentaje de personas pueden experimentar un ataque al ser expuestas a ciertas imágenes visuales, como luces o dibujos intermitentes que pueden aparecer en juegos de video o en otros contenidos electrónicos o en línea. Aún personas que no tienen historia de ataques o de epilepsia pueden tener una condición no diagnosticada que puede causar estos "ataques epilépticos fotosensibles" al estar viendo juegos de video u otros contenidos electrónicos. Estos ataques tienen una variedad de síntomas, incluyendo mareos, desorientación, confusión, pérdida momentánea de conciencia, crispación de ojos o cara, visión alterada o tirones o sacudidas de brazos o piernas. Si usted experimenta cualquiera de los síntomas anteriormente mencionados, o si usted o su familia tiene historia de ataques o epilepsia, debe de dejar inmediatamente de usar el Sitio Web y consultar un doctor.
 
4.      Leyes Aplicables. Nosotros controlamos y operamos el Sitio Web desde nuestras oficinas en los Estados Unidos de América. No representamos a los materiales en el Sitio Web como apropiados o disponibles para su uso en otros lugares. Las personas que escojan acceder al sitio Web desde otros lugares lo harán por su propia iniciativa y son responsables del cumplimiento de las leyes locales, si y al grado en que las leyes locales sean aplicables. Todas las partes sujetas a estos términos y condiciones renuncian a sus derechos respectivos a un juicio con jurado.
 
5.      Término.  Time Inc. puede terminar, cambiar, suspender o descontinuar cualquier aspecto del Sitio Web o de los servicios del Sitio Web en cualquier momento. Time Inc. puede restringir, suspender o terminar su acceso al Sitio Web y/o a sus servicios si creemos que usted está en incumplimiento de nuestros términos y condiciones o de la ley aplicable, o por cualquier otra razón sin notificación o responsabilidad. Time Inc. mantiene una política que estipula la terminación, en circunstancias apropiadas, de los privilegios de uso del Sitio Web para usuarios que son violadores repetitivos de los derechos de propiedad intelectual.
 
6.      Cambios de Términos de Uso.  Time Inc. se reserva el derecho, a su sola discreción, de cambiar, modificar, añadir o quitar cualquier porción de los Términos y Condiciones, toda o en parte, en cualquier momento. Los cambios en los Términos y Condiciones serán efectivos cuando se publiquen. La continuación del uso del Sitio Web y/o de los servicios puestos a disposición en o a través del Sitio Web después de haber sido publicado cualquier cambio, será considerado como aceptación de esos cambios.
 
7.      Misceláneos. Los Términos y Condiciones y la relación entre usted y nosotros, serán regidos por las leyes del Estado de Nueva York, Estados Unidos de América, sin consideración a conflictos de disposiciones de ley. Usted se obliga a que cualquier causa de acción legal que resulte bajo los Términos y Condiciones será iniciada y oída en la corte apropiada en el Estado de Nueva York, Condado de Nueva York, Estados Unidos de América. Usted se obliga a someterse a la jurisdicción personal y exclusiva de las cortes localizadas dentro del Condado de Nueva York en el Estado de Nueva York. Nuestra falla al ejercer y hacer valer cualquier derecho o disposición de los Términos y Condiciones no constituirá una renuncia a dicho derecho o disposición. Si cualquier disposición de los Términos y Condiciones es encontrada inválida por una corte de jurisdicción competente, las partes, sin embargo, están de acuerdo en que la corte deberá esforzarse en aplicar las intenciones de las partes como están reflejadas en la disposición, y las otras disposiciones de los Términos y Condiciones permanecen vigentes.
'],
            ['pais_id' => '15', 'terminos' => 'Terms and Conditions of Use of the Site 

            1. Featured Materials. Unless specifically requested, we do not ask or wish to receive any confidential, secret or proprietary information or other material from you through the Website, by email or otherwise. Any information, creative works, demonstrations, ideas, suggestions, concepts, methods, systems, designs, plans, techniques or other materials that you have sent or presented to us (including, without limitation, what you present or send to our groups ("Submitted Materials") will be considered as non-confidential or secret and may be used by us in any manner consistent with the Privacy Policy. Privacy of the Website. By submitting or submitting Submitted Materials to us, you: (i) represent and warrant that the Submitted Materials are your own, that no other person has any rights thereto, and that any "moral rights" to the Submitted Materials have been waived, and (Ii) you grant us and our affiliates royalty-free, royalty-free, worldwide, perpetual, irrevocable, non-exclusive and fully transferable rights and licenses, which may be assigned and sublicensed, used, copied, reproduced, Modify, adapt, publish, translate, create derivative works from, distribute, perform, display and incorporate in any other work any of the Submitted Materials (in whole or in part) in any form, medium or technology not known or to be developed, including promotional purposes And / or commercial. We can not be responsible for keeping any Submission You provided and we may delete or destroy said Submission at any time.

2. Prohibited User Conduct. You warrant and agree that, while using the Website and the various services and articles offered on or through the Website, you will not: (a) personalize any person or entity or misrepresent your affiliation with any other person Or entity; (B) insert your own advertisement, brand positioning or other promotional content or that of a third party in any of the contents, materials or services or materials of the Website (for example, without limitation, in an RSS update or in a program Recorded podcast received from Time Inc. or otherwise through the Website), nor will it use, redistribute, republish or exploit such content or services for any other commercial or promotional purposes; Nor (c) attempt to gain unauthorized access to other computer systems through the Website. You will not: (i) participate in surfing the web, scraping the screen, scraping the database, collecting e-mail addresses, wireless addresses, or other personal or contact information , Or any other automatic means of obtaining lists of users or other information from or through the Website or the services offered on or through the Website, including, without limitation, any information found on any related server or database With the Website or services offered on or through the Website; (Ii) obtain or attempt to gain unauthorized access to computer systems, materials or information by any means; (Iii) use the Website or services made available to you on or through the Website in any manner intended to disrupt, disable, disable, overburden, or impair the Website or such services, including, without limitation, sending messages Unsolicited bulk or flood servers with requests; (Iv) you will use the Website or the services or articles on the Website in violation of the intellectual property or other legal or patrimonial rights of Time Inc or any third party; Nor (v) use the Website or the services of the Website in violation of any applicable law. You further agree not to attempt (or encourage or support the intent of another) to deceive, destroy, decrypt, or otherwise alter or interfere with the Website or the services of the Website, or any content thereof , Or make any unauthorized use of it. You agree not to use the Website in any way that could damage, disable, overburden, or impair the Website or interfere with any other persons use or enjoyment of the Website or any of its services. You will not obtain or attempt to obtain any material or information through any means that has not been stipulated or made available to the public intentionally through the Website.
 
3. Public Forums. Time Inc. may from time to time have messaging services, chat services, news boards, blogs, other forums and other services available on or through the Website. In addition to any other regulations and regulations that we may publish with respect to a particular service, you agree not to upload, report, transmit, distribute or otherwise publish through the Website or any service or article made available In or through the Website, any material that (i) restrains or inhibits any other user from using and enjoying the Website or the services of the Website, (ii) is fraudulent, illegal, threatening, abusive, harassing, libelous Defamatory, obscene, vulgar, offensive, pornographic, profane, sexually explicit or indecent, (iii) constitutes or encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any local, state, national or (Iv) violate, infringe or infringe on the rights of third parties including, without limitation, copyright, trade marks, trade secrets, confidentiality, contracts, Patents, privacy or publicity rights or any other property rights, (v) contains a virus, spy or other harmful component, (vi) contains fixed links, advertising, chain letters or pyramid schemes of any kind, or (Vii) constitutes or contains indications of origin, endorsements or statements of false or misleading facts. You further agree not to impersonate any other person or entity, whether real or fictitious, including any Person of Time Inc. You may not offer to buy or sell any product or service in or through your comments submitted in our forums. Only you are responsible for the content and consequences of any of your activities.

4. Right of Monitoring and Editorial Control. Time Inc. reserves the right, but does not have the obligation, to monitor and / or review all materials sent to the Website or through the services or articles on the Website by users, and Time Inc. is not responsible for said Materials submitted by users. However, Time Inc. reserves the right at all times to disclose any information that is necessary to satisfy any law, regulation or governmental request, or to edit, refuse to place or remove any information or materials, in whole or in part, that At Time Incs sole discretion, are objectionable or in violation of these Terms of Use, Time Incs policies or applicable law. We may also impose limits on certain forum articles or restrict your access to all or part of the forums without notice or penalty if we believe you are in breach of the guidelines set forth in this paragraph, our terms and conditions or applicable law, or For any other reason without notice or liability.
 
5. Private or Delicate Information in Public Forums. It is important to remember that comments submitted in a forum can be recorded and stored in multiple places, both on our Website and elsewhere on the Internet, which may be accessible for a long time and have no control over who will eventually read them. It is therefore important that you be careful and selective about the personal information you disclose about yourself and others, and in particular, should not disclose sensitive, proprietary or confidential information in your comments in our public forums.
'],
            ['pais_id' => '184', 'terminos' => "Terms and Conditions of Use of the Site

            1. Links to the Website. You agree that if you include a link from any other website to the Website, that link will open in a new browser window and link to the full version of an HTML formatted page of this Website. You are not allowed to link directly to any image stored on the Website or our services, such as using an on-line link method to cause the image stored by us to be displayed on another website. You agree not to download or use images stored on this Website on another website, for any purpose, including, without limitation, posting such images on another website. You agree not to link from any other website to this Website in such a way that the Website, or any page of the Website, is 'framed', surrounded or overshadowed by the contents, materials or brand positions of any third party . We reserve all our rights under the law to insist that any link to the Website be discontinued and to revoke your right to link to the Website of any other website at any time we send you written notice.

2. Compensation. You agree to defend, indemnify and hold Time Inc. and the directors, officers, employees and agents of Time Inc. and its affiliates harmless from and against any and all claims, liabilities, costs and expenses of any nature, including Lawyers, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, attorneys, Time Inc. reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such event, you agree to cooperate with Time Inc. in defense Of said claim.
 
3. Orders of Products and Services. We may place certain products at the disposal of visitors and registered on the Website. If you order any product, you hereby represent and warrant that you are 18 years of age or older. You agree to pay the full price of any purchase you make, either with a credit / debit card concurrent with your order online or by another acceptable means of payment for Time Inc. You agree to pay all applicable taxes. If the payment is not received by us from the issuer of your credit or debit card or its agents, you agree to pay all amounts due at the time of the claim by us. Some products that you buy and / or download on or through the Website may be subject to additional terms and conditions that will be presented to you at the time of purchase or download.
 
4. Third Party Websites. You may link to the third party websites and third parties may link to the Website ('Linked Sites'). You acknowledge and agree that we have no responsibility for the information, content, products, services, advertisements, codes or other materials that may or may not be provided by or through the Linked Sites, even if they are owned by or are Directed by our affiliates. Links to Linked Sites do not constitute an endorsement or endorsement by us of such websites or the information, content, products, services, advertisements, codes or other materials presented on or through such websites. The inclusion of any link to such sites on our Site does not imply the endorsement, endorsement or recommendation of that Site of Time Inc. Time Inc. disclaims any liability for the links (1) of another website to this Website and (2) To another website of this Website. Time Inc. can not guarantee the standards of any website to which links are provided on this Website, nor will Time Inc. be responsible for the content of such sites, or any subsequent links. Time Inc. does not represent or warrant that the contents of any third party's website are accurate, comply with state or federal law, or comply with copyright laws or other intellectual property laws. Time Inc. is not responsible for any form of transmission received from any linked website. Any reliance placed on the contents of a third-party website is made at your own risk and you assume all the responsibilities and consequences that result from such trust.

5. Copyright Agent.
 
We respect the intellectual property rights of others and require that persons using the Website, or the services or articles made available to them on or through the Website, do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, please send the following information to Time Inc. Copyright Agent, designated as such in accordance with the web page named down:
 
• Your address, telephone number and email address;
• A description of the copyrighted work that you claim has been infringed;
• A description of where the alleged infringing material is located;
• A statement by you that you believe in good faith that the disputed use is not authorized by the copyright owner, its agent or the law;
• An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; Y
• A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on behalf of the copyright owner.
"],
            ['pais_id' => '39', 'terminos' => "Terms and Conditions of Use of the Site

            1. DISCLAIMER OF WARRANTIES. THE WEBSITE, INCLUDING, WITHOUT LIMITATION, ALL SERVICES, CONTENT, FUNCTIONS, AND MATERIALS PROVIDED THROUGH THE WEBSITE, ARE PROVIDED 'AS IS,' 'AS SET FORTH', WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF INFORMATION, DATA, DATA PROCESSING SERVICES, UNLIMITED OR UNINTERRUPTED ACCESS, ANY WARRANTY WITH RESPECT TO AVAILABILITY, INTERPRETABILITY, NON-INTERPRETABILITY, ACCURACY, ACCURACY, REFTITUDE, PERFECTION, CONCLUSION, UTILITY, OR CONTENT OF INFORMATION, AND ANY WARRANTY OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, AND HEREBY DISCLAIM ANY AND ALL SUCH WARRANTIES, EXPRESS AND IMPLIED. WE DO NOT WARRANT THAT THE WEBSITE OR THE SERVICES, CONTENT, FUNCTIONS OR MATERIALS PROVIDED THROUGH THE WEBSITE WILL BE TIMELY, SECURE, UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED. WE DO NOT WARRANT THAT THE WEBSITE OR THAT THE SERVICES PROVIDED WILL MEET USER REQUIREMENTS. NO ADVICE, RESULTS OR INFORMATION, WHETHER ORAL OR WRITTEN, YOU OBTAIN FROM US THROUGH THE WEBSITE, CREATE ANY WARRANTY THAT HAS NOT BEEN EXPRESSLY SET FORTH HEREIN. TIME INC. NEITHER ASSUMES ANY LIABILITY, AND I WILL NOT BE LIABLE FOR ANY DAMAGES TO, OR ANY VIRUS THAT COULD INFECT YOUR EQUIPMENT BECAUSE OF YOUR ACCESS TO, USE OF, OR NAVIGATION ON THE WEBSITE OR DOWNLOAD ANY OF THE MATERIALS, DATA, TEXTS , IMAGES, CONTENT OF VIDEO OR AUDIO CONTENT OF THE WEBSITE. IF YOU ARE NOT SATISFIED WITH THE WEB SITE, YOUR SOLE REMEDY IS TO DISCONTINUE USING THE WEBSITE.
WE TRY TO ENSURE THAT THE INFORMATION PUBLISHED ON THE WEBSITE IS CORRECT AND UPDATED. WE RESERVE THE RIGHT TO CHANGE OR MAKE CORRECTIONS TO ANY INFORMATION PROVIDED ON THE WEBSITE AT ANY TIME AND WITHOUT ANY PRIOR NOTICE. TIME INC. NEITHER AVALA IS NOT RESPONSIBLE FOR THE ACCURACY OR VERACITY OF ANY OPINION, ADVICE OR DECLARATION ON THE WEBSITE, OR ANY OFFENSIVE, DEFAMATORY, OBSCENE, INDIRECT, ILLEGAL, OR VIOLATORY PUBLICATION MADE BY ANYONE OTHER THAN ANY PERSON OTHER THAN A PORTAVOZ EMPLOYEE AUTHORIZED BY TIME INC. IN ITS OFFICIAL CHARACTER (INCLUDING, WITHOUT LIMITATION, OTHER USERS OF THE WEBSITE). IT IS YOUR LIABILITY TO EVALUATE THE ACCURACY, CONCLUSION OR UTILITY OF ANY INFORMATION, OPINION, ADVICE OR OTHER CONTENT AVAILABLE THROUGH THE WEBSITE. PLEASE SEARCH THE PROFESSIONALS COUNCIL, AS APPROPRIATE, WITH RESPECT TO THE EVALUATION OF ANY INFORMATION, OPINION, ADVICE, OR OTHER SPECIFIC CONTENT, INCLUDING BUT NOT LIMITED TO, INFORMATION, OPINION, ADVICE, OR OTHER FINANCIAL, HEALTH, OR STYLE CONTENT OF LIFE.
 
PRIOR TO MAKING A PURCHASE OR SALE OF ANY VALUE OR INVESTMENT, WE ASK YOU TO CONSULT WITH YOUR RUNNER OR ANOTHER FINANCIAL ADVISER TO VERIFY PRICES AND OTHER INFORMATION. WE WILL HAVE NO LIABILITY FOR INVESTMENT DECISIONS BASED ON, OR RESULTS OBTAINED FROM, THE CONTENT PROVIDED HEREIN. NOTHING CONTAINED IN THE WEBSITE WILL BE INTERPRETED AS AN INVESTMENT BOARD. TIME INC. IT IS NOT A REGISTERED BROKER OR AN INVESTMENT CONSULTANT AND DOES NOT GIVE INVESTMENT ADVICE OR RECOMMEND ONE PRODUCT OVER ANY.
 
WITHOUT LIMITATION AS PROVIDED IN THIS SECTION, TIME INC, AND ITS AFFILIATES, SUPPLIERS AND LICENSORS MAKE NO WARRANTIES OR REPRESENTATIONS REGARDING ANY PRODUCTS OR SERVICES ORDINATED OR PROVIDED VIA THE WEBSITE, AND HEREBY DISCLAIM, AND YOU HEREBY DISCLAIM, ANY AND ALL WARRANTIES AND REPRESENTATIONS MADE TO LITERATURE ON PRODUCTS OR SERVICES, TO QUESTIONS COMMONLY MADE IN DOCUMENTS AND ANY OTHER WAY ON THE WEBSITE OR IN CORRESPONDENCE WITH TIME INC. OR WITH ITS AGENTS. ANY PRODUCT OR SERVICE ORDINATED OR PROVIDED VIA THE WEBSITE IS PROVIDED BY TIME INC. 'AS IS', EXCEPT TO THE DEGREE, IF THE CASE, IS OTHERWISE ESTABLISHED IN WRITING, IN A LICENSE AGREEMENT OR SALES CELEBRATED BY SEPARATE BETWEEN YOU AND TIME INC. OR YOUR SUPPLIER OR THE PERSON GIVING THE LICENSE.

2. LIMIT OF LIABILITY. IN NO EVENT WILL, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, TIME INC., OR ANY OF ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS OR SUPPLIERS, CONTENT OR SERVICES (CONSTANTLY, 'PROTECTED ENTITIES') FROM ANY DIRECT DAMAGES INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES AS A RESULT OF, OR DIRECTLY OR INDIRECTLY RELATED TO, THE USE OF OR INABILITY TO USE THE WEB SITE OR THE CONTENTS, MATERIALS AND FUNCTIONS RELATED TO THE SAME, INFORMATION THROUGH THE WEB SITE, LOST BUSINESS OR LOST SALES, EVEN IF SUCH PROTECTED ENTITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE ABOVE LIMITATIONS DO NOT APPLY TO SOME USERS. IN NO EVENT WILL THE ENTITIES PROTECTED BY OR IN CONNECTION WITH ANY CONTENT PUBLISHED, TRANSMITTED, EXCHANGEED OR RECEIVED BY OR ON BEHALF OF ANY USER OR OTHER PERSON ON OR THROUGH THE WEBSITE. IN NO EVENT SHALL THE TOTAL SUM OF THE RESPONSIBILITIES OF THE ENTITIES PROTECTED TO YOU, FOR ANY DAMAGES, LOSSES AND CAUSES OF PENALTY (WHETHER IN CONTRACT OR TORT, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE OR OTHERWISE) THAT RESULT OF THE TERMS AND CONDITIONS OR YOUR USE OF THE WEBSITE, SHALL EXCEED THE TOTAL AMOUNT, THE AMOUNT, IF ANY, PAID BY YOU TO TIME INC. BY THE USE OF THE WEBSITE OR BY THE PURCHASE OF PRODUCTS VIA THE WEBSITE.
 
3. Photosensitive attacks. A very small percentage of people may experience an attack by being exposed to certain visual images, such as flashing lights or drawings that may appear in video games or other electronic or online content. Even people who have no history of seizures or epilepsy may have an undiagnosed condition that can cause these 'photosensitive epileptic seizures' when viewing video games or other electronic content. These attacks have a variety of symptoms, including dizziness, disorientation, confusion, momentary loss of consciousness, twitching of the eyes or face, impaired vision, or jerking or jerking of arms or legs. If you experience any of the above symptoms, or if you or your family has a history of seizures or epilepsy, you should immediately stop using the Website and consult a doctor.
 
4. Applicable Laws. We control and operate the Website from our offices in the United States of America. We do not represent materials on the Website as appropriate or available for use in other locations. Individuals who choose to access the Website from other locations will do so on their own initiative and are responsible for compliance with local laws, if and to the extent that local laws are applicable. All parties subject to these terms and conditions waive their respective rights to a jury trial.

5. Term. Time Inc. may terminate, change, suspend or discontinue any aspect of the Website or the services of the Website at any time. Time Inc. may restrict, suspend or terminate your access to the Website and / or its services if we believe that you are in breach of our terms and conditions or applicable law, or for any other reason without notice or liability. Time Inc. maintains a policy that provides for the termination, under appropriate circumstances, of the use privileges of the Website for users who are repetitive violators of intellectual property rights.
 
6. Changes to Terms of Use. Time Inc. reserves the right, in its sole discretion, to change, modify, add or remove any portion of the Terms and Conditions, in whole or in part, at any time. Changes to the Terms and Conditions will be effective when they are posted. Continued use of the Website and / or services made available on or through the Website after any changes have been posted will be deemed to be acceptance of those changes.
 
7. Miscellaneous. The Terms and Conditions and the relationship between you and us shall be governed by the laws of the State of New York, United States of America, without regard to conflicts of law provisions. You agree that any cause of legal action that results under the Terms and Conditions will be initiated and heard in the appropriate court in the State of New York, New York County, United States of America. You agree to submit to the personal and exclusive jurisdiction of the courts located within New York County in the State of New York. Our failure to exercise and enforce any right or provision of the Terms and Conditions shall not constitute a waiver of such right or provision. If any provision of the Terms and Conditions is found to be invalid by a court of competent jurisdiction, the parties, however, agree that the court shall endeavor to enforce the intentions of the parties as reflected in the provision, and the other Provisions of the Terms and Conditions remain in force.
"],
            ['pais_id' => '239', 'terminos' => 'Términos y Condiciones de Uso del Sitio

            Los siguientes términos y condiciones (los "Términos y Condiciones") rigen el uso que usted le dé a este sitio web y a cualquiera de los contenidos disponibles por o a través de este sitio web, incluyendo cualquier contenido derivado del mismo (el "Sitio Web"). Time Inc. ("Time Inc." o "nosotros") ha puesto a su disposición el Sitio Web. Podemos cambiar los Términos y Condiciones de vez en cuando, en cualquier momento sin ninguna notificación, sólo publicando los cambios en el Sitio Web. AL USAR EL SITIO WEB, USTED ACEPTA Y ESTÉ DE ACUERDO CON ESTOS TÉRMINOS Y CONDICIONES EN LO QUE SE REFIERE A SU USO DEL SITIO WEB. Si usted no está de acuerdo con estos Términos y Condiciones, no puede tener acceso al mismo ni usar el Sitio Web de ninguna otra manera.
 
1.         Derechos de Propiedad. Entre usted y Time Inc., Time Inc. es dueño único y exclusivo, de todos los derechos, título e intereses en y del Sitio Web, de todo el contenido (incluyendo, por ejemplo, audio, fotografías, ilustraciones, gráficos, otros medios visuales, videos, copias, textos, software, títulos, archivos de Onda de choque, etc.), códigos, datos y materiales del mismo, el aspecto y el ambiente, el diseño y la organización del Sitio Web y la compilación de los contenidos, códigos, datos y los materiales en el Sitio Web, incluyendo pero no limitado a, cualesquiera derechos de autor, derechos de marca, derechos de patente, derechos de base de datos, derechos morales, derechos sui generis y otras propiedades intelectuales y derechos patrimoniales del mismo. Su uso del Sitio Web no le otorga propiedad de ninguno de los contenidos, códigos, datos o materiales a los que pueda acceder en o a través del Sitio Web.
 
2.         Licencia Limitada. Usted puede acceder y ver el contenido del Sitio Web desde su computadora o desde cualquier otro aparato y, a menos de que se indique de otra manera en estos Términos y Condiciones o en el Sitio Web, sacar copias o impresiones individuales del contenido del Sitio Web para su uso personal, interno únicamente. El uso del Sitio Web y de los servicios que se ofrecen en o a través del Sitio Web, son sólo para su uso personal, no comercial.
 
3.         Uso Prohibido. Cualquier distribución, publicación o explotación comercial o promocional del Sitio Web, o de cualquiera de los contenidos, códigos, datos o materiales en el Sitio Web, está estrictamente prohibida, a menos de que usted haya recibido el previo permiso expreso por escrito del personal autorizado de Time Inc. o de algún otro poseedor de derechos aplicable. A no ser como está expresamente permitido en el presente contrato, usted no puede descargar, informar, exponer, publicar, copiar, reproducir, distribuir, transmitir, modificar, ejecutar, difundir, transferir, crear trabajos derivados de, vender o de cualquier otra manera explotar cualquiera de los contenidos, códigos, datos o materiales en o disponibles a través del Sitio Web. Usted se obliga además a no alterar, editar, borrar, quitar, o de otra manera cambiar el significado o la apariencia de, o cambiar el propósito de, cualquiera de los contenidos, códigos, datos o materiales en o disponibles a través del Sitio Web, incluyendo, sin limitación, la alteración o retiro de cualquier marca comercial, marca registrada, logo, marca de servicios o cualquier otro contenido de propiedad o notificación de derechos de propiedad. Usted reconoce que no adquiere ningún derecho de propiedad al descargar algún material con derechos de autor de o a través del Sitio Web. Si usted hace otro uso del Sitio Web, o de los contenidos, códigos, datos o materiales que ahí se encuentren o que estén disponibles a través del Sitio Web, a no ser como se ha estipulado anteriormente, usted puede violar las leyes de derechos de autor y otras leyes de los Estados Unidos y de otros países, así como las leyes estatales aplicables, y puede ser sujeto a responsabilidad legal por dicho uso no autorizado.
 
4.         Marcas Comerciales. Las marcas comerciales, logos, marcas de servicios, marcas registradas (conjuntamente las "Marcas Comerciales") expuestas en el Sitio Web o en los contenidos disponibles a través del Sitio Web son Marcas Comerciales de Time Inc. registradas y no registradas y otras, y no pueden ser usadas con respecto a productos y/o servicios que no estén relacionados, asociados o patrocinados por sus poseedores de derechos y que puedan causar confusión a los clientes, o de alguna manera que denigre o desacredite a sus poseedores de derechos. Todas las Marcas Comerciales que no sean de Time Inc. que aparezcan en el sitio Web o en o a través de los servicios del Sitio Web, si las hubiera, son propiedad de sus respectivos dueños. Nada que esté contenido en el Sitio Web deberá ser interpretado como otorgando, por implicación, desestimación, o de otra manera, alguna licencia o derecho para usar alguna Marca Comercial expuesta en el Sitio Web sin el permiso escrito de Time Inc. o de terceros que puedan ser dueños de dicha Marca Comercial. El mal uso de las Marcas Comerciales expuestas en el Sitio Web o en o a través de cualquiera de los servicios del Sitio Web está estrictamente prohibido.
 
5.         Información del Usuario. En el curso del uso que usted haga del Sitio Web y/o de los servicios puestos a su disposición en o a través del Sitio Web, se le puede pedir que nos proporcione cierta información personalizada (dicha información en lo sucesivo "Información del Usuario"). Las políticas de uso y recopilación de información de Time Inc. con respecto a la privacidad de dicha Información del Usuario se establecen en la Politica de Privacidad del Sitio Web, la cual está incorporada al mismo como referencia para todos los propósitos. Usted reconoce y acepta ser el único responsable de la exactitud del contenido de la Información del Usuario.
'],
            
        ];

        DB::table('terminos')->insert($terminos);
    }
}
